### ISSUE TITLE
Hello World 

### ISSUE THREAD

**Issue by honeybhardwaj** [Robotics-Club-BMU/Processing_maniac#17]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
The Processing equivalent of a "Hello World" program is simply to draw a line. create a program to do that and put it in script and make a readme file explaining you code and adding ss for the output.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by KrishnaBMU** [comment]
Hey, can you assign me this.
