### ISSUE TITLE
Write a code to generate pie chart in processing

### ISSUE THREAD

**Issue by honeybhardwaj** [Robotics-Club-BMU/Processing_maniac#33]
**Is your feature request related to a problem? Please describe.**
generate a pie chart from data stored in array.

**Describe the solution you'd like**
the chart should use the array and convert that data into pie chart. the array will consist of degree of each data.The file needs to be added in scripts with proper code explanation and updation in table of content. also include output images

**Additional context**
![Screenshot from 2021-10-21 16-55-39](https://user-images.githubusercontent.com/51120790/138268513-23ad9ead-fb60-4e48-a7a2-da55f0273ba4.png)

**Comment by KrishnaBMU** [comment]
Hey, can you assign this to me.
