### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by honeybhardwaj** [Robotics-Club-BMU/Processing_maniac#4]
Hi,
You need to create an issue template and can refer to the following link to learn more about it
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Thanks

**Comment by tb-rules10** [comment]
ok actually i thought i was the first person so i didi it instantly
thnx btw :)

**Comment by tb-rules10** [comment]
actually i wasn't sure coz it wasn't showing an option at first
Np
