### ISSUE TITLE
Create a Template for Pull Request

### ISSUE THREAD

**Issue by honeybhardwaj** [Robotics-Club-BMU/Processing_maniac#9]
Hi,
Please refer the link to know more https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by Exentric24** [comment]
Please assign me this issue!

**Comment by honeybhardwaj** [comment]
> Please assign me this issue!

cool go ahead if you have any doubts discuss it with me

**Comment by Exentric24** [comment]
What should I include in the file after creating it?
